seed: 0
val_split_size: 0.1
deterministic: true

pipeline:
  name: boosted_mlp_head.BoostedMLPHeadModel

  # embeddings
  embed_type: mean
  embed_pipeline: huggingface
  embed_model: microsoft/deberta-v3-base

  # model params
  n_learners: 8
  hidden_sizes: [128]
  dropout_p: 0.3

  # training args
  mode: regression  # regression, classification
  num_epochs: 5
  boost_rate: 0.1
  batch_size: 64
