seed: 0
val_split_size: 0.1
deterministic: true

pipeline:
  name: classical_ml.ClassicalMLPipeline
  label_mapping: classification

  percent_train_samples: 0.05

  vectorizer:
      type: CountVectorizer
      ngram_range: [1, 3]
      max_features: 100000

  model:
      type: SVC
      C: 1.0
      kernel: rbf
      verbose: True

  preprocessing:
    - clean_whitespaces
    - internet
    - punctuation
    - contractions
    - remove_repeated_chars
    - remove_special_chars
    - remove_stopwords
    - lowercase
    - lemmatize
