seed: 0
val_split_size: 0.1
deterministic: true

pipeline:
  name: classical_ml.ClassicalMLPipeline
  label_mapping: classification

  vectorizer:
      type: CountVectorizer
      ngram_range: [1, 3]
      max_features: 100000

  model:
      type: OneVsRestClassifier
      n_jobs: -1
      verbose: True
      estimator:
          type: SVC
          C: 1.0
          kernel: rbf
