seed: 0
val_split_size: 0.1
deterministic: true

pipeline:
  name: classical_ml.ClassicalMLPipeline
  label_mapping: classification

  vectorizer:
    type: CountVectorizer
    ngram_range: [1, 3]
    max_features: 100000

  model:
    type: StackingClassifier
    n_jobs: -1

    estimators:
      - type: LogisticRegression
        C: 1.0
        max_iter: 100
        n_jobs: -1

      - type: XGBClassifier
        n_estimators: 100
        max_depth: 25
        n_jobs: -1

      - type: SVC
        C: 0.7
        kernel: rbf

  preprocessing:
    - clean_whitespaces
    - internet
    - punctuation
    - contractions
    - remove_repeated_chars
    - remove_special_chars
    - remove_stopwords
    - lowercase
    - lemmatize
