seed: 0
val_split_size: 0.1
deterministic: true

pipeline:
  name: mlp_head.MLPHeadModel

  embed_type: mean
  embed_pipeline: huggingface
  embed_model: FacebookAI/roberta-large

  mode: regression
  num_epochs: 25
  batch_size: 64
  patience: 8
